#!/bin/bash
set -euo pipefail

echo "This is from the pre command hook"

echo "--- Verify node.js version"
node -v

hash gh 2>/dev/null || {
  echo "-- Installing Github CLI"
  apt update && apt install gh -y
}